name: update-version
on:
  repository_dispatch:
    types: [update-version]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print all
        run: echo "${{ github.event.client_payload.new_version }} ${{ github.event.client_payload.docker_repo }} ${{ github.client_payload.inputs.k8s_project }} ${{ github.event.client_payload.k8s_namespace }} ${{ github.event.clien_payload.env }}"